# Generated by Django 6.0.2 on 2026-04-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_is_active_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
    ]
